### ISSUE TITLE
Autogenerate MITER ATT&CK tags

### ISSUE THREAD

**Issue by mssalvatore** [guardicode/monkeyevents#3]
## Description

Presently, MITRE ATT&CK tags are added to this package piecemeal as they are needed by specific plugins or features. A much better approach would be to automatically generate all tags from a specific version of the MITRE ATT&CK framework.

## Tasks

- [x] Find a stable mechanism for pulling/consuming the MITRE ATT&CK framework techniques
- [x] Write a utility script that can consume the techniques and transform them into Python code. (Same format as https://github.com/guardicode/monkeyevents/blob/d75e849789e1b79975985ce0f9820c9498255394/monkeyevents/tags/attack.py)
- [x] Replace [`monkeyevents.tags.attack`](https://github.com/guardicode/monkeyevents/blob/d75e849789e1b79975985ce0f9820c9498255394/monkeyevents/tags/attack.py) with the autogenerated code from the previous task.

**Comment by mssalvatore** [comment]
Released in v0.4.0
